sudo: false
language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4"

script:
  - npm install
  - npm run lint
  - npm run test

after_success:
  - npm run coverage
  - npm run codecov

notifications:
  email: false
